### ISSUE TITLE
Github Actions를 이용한 자동 배포 및 동기화

### ISSUE THREAD

**Issue by dehehe-mirai** [newbiepr/shinymaskr#2]
원본 레포지토리(https://github.com/biuuu/ShinyColors/tree/master/.github/workflows/data.yml) 를 보면 data를 다른 브랜치로 관리하고 있고, 매 20시마다 (0 20 * * *) "ShinyGroup/SCTranslationData" 레포지토리에서 파일을 가져와 data 브랜치와 동기화합니다.

이를 따라하면 한패시트 일단위 자동 동기화가 가능할텐데,  혹시 생각 있으시면 테스트를 위해 콜라보 권한 부탁드립니다.

**Comment by ImBada** [comment]
저희 시트 구조가 저쪽이랑 많이 달라서 수작업이 많습니다. 이쪽으로 관리하고 있는 게 있어서 자동화할 계획이 딱히 없습니다.
